title: "Stroud ADHD Collective"
description: "A website for showcasing the recent activity of and events hosted by a group of ADHDers local to Stroud, Gloucestershire."
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme